{% set name = "wxutils" %}
{% set version = "0.3.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d365e7c95feb0327ea65339ec4ff90d1502f4ea8cc8e9350c87fc6598f2b4af5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools >=45
    - wheel
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - darkdetect
    - pyshortcuts >= 1.9.6
    - wxpython >=4.2.2

test:
  imports:
    - wxutils

about:
  home: https://github.com/newville/wxutils
  license: MIT
  license_file: LICENSE
  summary: Utilities and convenience classes and functions for wxPython

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - newville
    - maurov
    - conda-forge/event-model
